version: "3"

networks:
  loki:

services:
  web-app-python:
    build: ../app_python
    ports:
      - "8080:8080"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: bash -c ':> /dev/tcp/localhost/8080' || exit 1
      interval: 1m
      timeout: 3s
      retries: 3
    volumes:
      -  ./app-py-vol:/app/vol

  web-app-java:
    build: ../app_java
    ports:
      - "8081:8080"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1
      interval: 1m
      timeout: 3s
      retries: 3
    volumes:
      - ./app-java-vol:/app/vol
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1
      interval: 1m
      timeout: 3s
      retries: 3

  promtail:
    image: grafana/promtail
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: bash -c ':> /dev/tcp/localhost/9080' || exit 1
      interval: 1m
      timeout: 3s
      retries: 3

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      interval: 1m
      timeout: 3s
      retries: 3

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/ || exit 1
      interval: 1m
      timeout: 3s
      retries: 3