- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Install docker-compose
  ansible.builtin.pip:
    name: docker-compose
    state: present
