name: app python

on:
  push:
    paths:
      - "app_python/**"
      - "app_java/**"

jobs:
  build-app-pipeline:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"
          cache: "pip"
          cache-dependency-path: "app_python/requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app_python/requirements.txt

      - name: Run linter
        working-directory: app_python
        run: |
          pip install flake8
          flake8

      - name: Test app
        working-directory: app_python
        run: |
          pip install pytest
          pytest test.py

  snyk:
    needs: build-app-pipeline
    timeout-minutes: 5

    name: Run Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master
        with:
          args: --skip-unresolved app_python/
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    needs:
      - build-app-pipeline
      - snyk
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push python app
        uses: docker/build-push-action@v5
        with:
          context: app_python
          file: app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-py-img:latest